//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchandiserBot.PwdChange {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ChangeResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResultMessage {
            get {
                return this.ResultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultMessageField, value) != true)) {
                    this.ResultMessageField = value;
                    this.RaisePropertyChanged("ResultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PwdChange.wsPwdChangeSoap")]
    public interface wsPwdChangeSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  Emp_NO 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/userPwdChange", ReplyAction="*")]
        MerchandiserBot.PwdChange.userPwdChangeResponse userPwdChange(MerchandiserBot.PwdChange.userPwdChangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/userPwdChange", ReplyAction="*")]
        System.Threading.Tasks.Task<MerchandiserBot.PwdChange.userPwdChangeResponse> userPwdChangeAsync(MerchandiserBot.PwdChange.userPwdChangeRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  Emp_NO 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/userPwdChangeFO", ReplyAction="*")]
        MerchandiserBot.PwdChange.userPwdChangeFOResponse userPwdChangeFO(MerchandiserBot.PwdChange.userPwdChangeFORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/userPwdChangeFO", ReplyAction="*")]
        System.Threading.Tasks.Task<MerchandiserBot.PwdChange.userPwdChangeFOResponse> userPwdChangeFOAsync(MerchandiserBot.PwdChange.userPwdChangeFORequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userPwdChangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userPwdChange", Namespace="http://tempuri.org/", Order=0)]
        public MerchandiserBot.PwdChange.userPwdChangeRequestBody Body;
        
        public userPwdChangeRequest() {
        }
        
        public userPwdChangeRequest(MerchandiserBot.PwdChange.userPwdChangeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class userPwdChangeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Emp_NO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OldPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NewPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string APFrom;
        
        public userPwdChangeRequestBody() {
        }
        
        public userPwdChangeRequestBody(string Emp_NO, string OldPwd, string NewPwd, string APFrom) {
            this.Emp_NO = Emp_NO;
            this.OldPwd = OldPwd;
            this.NewPwd = NewPwd;
            this.APFrom = APFrom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userPwdChangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userPwdChangeResponse", Namespace="http://tempuri.org/", Order=0)]
        public MerchandiserBot.PwdChange.userPwdChangeResponseBody Body;
        
        public userPwdChangeResponse() {
        }
        
        public userPwdChangeResponse(MerchandiserBot.PwdChange.userPwdChangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class userPwdChangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MerchandiserBot.PwdChange.ChangeResult userPwdChangeResult;
        
        public userPwdChangeResponseBody() {
        }
        
        public userPwdChangeResponseBody(MerchandiserBot.PwdChange.ChangeResult userPwdChangeResult) {
            this.userPwdChangeResult = userPwdChangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userPwdChangeFORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userPwdChangeFO", Namespace="http://tempuri.org/", Order=0)]
        public MerchandiserBot.PwdChange.userPwdChangeFORequestBody Body;
        
        public userPwdChangeFORequest() {
        }
        
        public userPwdChangeFORequest(MerchandiserBot.PwdChange.userPwdChangeFORequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class userPwdChangeFORequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Emp_NO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NewPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string APFrom;
        
        public userPwdChangeFORequestBody() {
        }
        
        public userPwdChangeFORequestBody(string Emp_NO, string NewPwd, string APFrom) {
            this.Emp_NO = Emp_NO;
            this.NewPwd = NewPwd;
            this.APFrom = APFrom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userPwdChangeFOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userPwdChangeFOResponse", Namespace="http://tempuri.org/", Order=0)]
        public MerchandiserBot.PwdChange.userPwdChangeFOResponseBody Body;
        
        public userPwdChangeFOResponse() {
        }
        
        public userPwdChangeFOResponse(MerchandiserBot.PwdChange.userPwdChangeFOResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class userPwdChangeFOResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MerchandiserBot.PwdChange.ChangeResult userPwdChangeFOResult;
        
        public userPwdChangeFOResponseBody() {
        }
        
        public userPwdChangeFOResponseBody(MerchandiserBot.PwdChange.ChangeResult userPwdChangeFOResult) {
            this.userPwdChangeFOResult = userPwdChangeFOResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsPwdChangeSoapChannel : MerchandiserBot.PwdChange.wsPwdChangeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsPwdChangeSoapClient : System.ServiceModel.ClientBase<MerchandiserBot.PwdChange.wsPwdChangeSoap>, MerchandiserBot.PwdChange.wsPwdChangeSoap {
        
        public wsPwdChangeSoapClient() {
        }
        
        public wsPwdChangeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsPwdChangeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPwdChangeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPwdChangeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MerchandiserBot.PwdChange.userPwdChangeResponse MerchandiserBot.PwdChange.wsPwdChangeSoap.userPwdChange(MerchandiserBot.PwdChange.userPwdChangeRequest request) {
            return base.Channel.userPwdChange(request);
        }
        
        public MerchandiserBot.PwdChange.ChangeResult userPwdChange(string Emp_NO, string OldPwd, string NewPwd, string APFrom) {
            MerchandiserBot.PwdChange.userPwdChangeRequest inValue = new MerchandiserBot.PwdChange.userPwdChangeRequest();
            inValue.Body = new MerchandiserBot.PwdChange.userPwdChangeRequestBody();
            inValue.Body.Emp_NO = Emp_NO;
            inValue.Body.OldPwd = OldPwd;
            inValue.Body.NewPwd = NewPwd;
            inValue.Body.APFrom = APFrom;
            MerchandiserBot.PwdChange.userPwdChangeResponse retVal = ((MerchandiserBot.PwdChange.wsPwdChangeSoap)(this)).userPwdChange(inValue);
            return retVal.Body.userPwdChangeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MerchandiserBot.PwdChange.userPwdChangeResponse> MerchandiserBot.PwdChange.wsPwdChangeSoap.userPwdChangeAsync(MerchandiserBot.PwdChange.userPwdChangeRequest request) {
            return base.Channel.userPwdChangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MerchandiserBot.PwdChange.userPwdChangeResponse> userPwdChangeAsync(string Emp_NO, string OldPwd, string NewPwd, string APFrom) {
            MerchandiserBot.PwdChange.userPwdChangeRequest inValue = new MerchandiserBot.PwdChange.userPwdChangeRequest();
            inValue.Body = new MerchandiserBot.PwdChange.userPwdChangeRequestBody();
            inValue.Body.Emp_NO = Emp_NO;
            inValue.Body.OldPwd = OldPwd;
            inValue.Body.NewPwd = NewPwd;
            inValue.Body.APFrom = APFrom;
            return ((MerchandiserBot.PwdChange.wsPwdChangeSoap)(this)).userPwdChangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MerchandiserBot.PwdChange.userPwdChangeFOResponse MerchandiserBot.PwdChange.wsPwdChangeSoap.userPwdChangeFO(MerchandiserBot.PwdChange.userPwdChangeFORequest request) {
            return base.Channel.userPwdChangeFO(request);
        }
        
        public MerchandiserBot.PwdChange.ChangeResult userPwdChangeFO(string Emp_NO, string NewPwd, string APFrom) {
            MerchandiserBot.PwdChange.userPwdChangeFORequest inValue = new MerchandiserBot.PwdChange.userPwdChangeFORequest();
            inValue.Body = new MerchandiserBot.PwdChange.userPwdChangeFORequestBody();
            inValue.Body.Emp_NO = Emp_NO;
            inValue.Body.NewPwd = NewPwd;
            inValue.Body.APFrom = APFrom;
            MerchandiserBot.PwdChange.userPwdChangeFOResponse retVal = ((MerchandiserBot.PwdChange.wsPwdChangeSoap)(this)).userPwdChangeFO(inValue);
            return retVal.Body.userPwdChangeFOResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MerchandiserBot.PwdChange.userPwdChangeFOResponse> MerchandiserBot.PwdChange.wsPwdChangeSoap.userPwdChangeFOAsync(MerchandiserBot.PwdChange.userPwdChangeFORequest request) {
            return base.Channel.userPwdChangeFOAsync(request);
        }
        
        public System.Threading.Tasks.Task<MerchandiserBot.PwdChange.userPwdChangeFOResponse> userPwdChangeFOAsync(string Emp_NO, string NewPwd, string APFrom) {
            MerchandiserBot.PwdChange.userPwdChangeFORequest inValue = new MerchandiserBot.PwdChange.userPwdChangeFORequest();
            inValue.Body = new MerchandiserBot.PwdChange.userPwdChangeFORequestBody();
            inValue.Body.Emp_NO = Emp_NO;
            inValue.Body.NewPwd = NewPwd;
            inValue.Body.APFrom = APFrom;
            return ((MerchandiserBot.PwdChange.wsPwdChangeSoap)(this)).userPwdChangeFOAsync(inValue);
        }
    }
}
